### PR TITLE
(ruka) convert velero to use external-secrets

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Review by cbarria — APPROVED** [review]
Looks Great 👍🏻

**Review by csilva-cl — COMMENTED** [review]
Seems fine. 

Should we also remove the last paragraphs of explanation of velero in velero.sh ?

**Comment by jhoblitt** [comment]
> Should we also remove the last paragraphs of explanation of velero in velero.sh ?

Are those instructions still relevant?

**Comment by csilva-cl** [comment]
Yes, I was wondering if they are going to be problem for fleet. Let's leave them then.

**Pull request merged**
