### PR TITLE
(namkueyen) k8s cluster configuration 

### PR DESCRIPTION
**Pull request by dtapiacl**
First revision of namkueyen cluster configuration.

### CODE REVIEW

**Review by jhoblitt — CHANGES_REQUESTED** [review]
A couple of issue:

- PR needs a more descriptive title. We particularly don't want "It 4410" in the title as that isn't even a jira slug.
- `kueyen/rke/cluster.yml` shouldn't have any changes being made to it as that cluster still exists.
- The branch needs to be rebased on current master.
- The body of the PR message will be part of the permanent record in the git repo as a merge commit. It isn't necessary to ask for review -- everyone should know what it means to be assigned as a PR reviewer on github.

**Review by dtapiacl — COMMENTED** [review]
Update to cluster configuration.

**Review by jhoblitt — CHANGES_REQUESTED** [review]
The PR message body still needs to be updated.

**Review by jhoblitt — APPROVED** [review]
LGTM

**Pull request merged**
