### PR TITLE
(pillan) add ccs cluster secret store & user

### PR DESCRIPTION
**Pull request by dtapiacl**

### CODE REVIEW

**Review by jhoblitt — CHANGES_REQUESTED** [review]
The config looks good one of the commit message isn't very informative.  I would expect that commit message to mention the addition of a new ClusterSecretStore to pillan.

image

**Review by jhoblitt — CHANGES_REQUESTED** [review]
What is the name of the resource being added? 

image

**Comment by dtapiacl** [comment]
> What is the name of the resource being added?
> 
> image

CCS Cluster Secret Store

**Review by jhoblitt — CHANGES_REQUESTED** [review]
The PR title is now:
image

An adjective (E.g. `add`) would be helpful but my main concern is that this PR doesn't create a bucket.  The goal is try to inform someone viewing `git log` as to what change the PR/changeset contains.

**Review by jhoblitt — APPROVED** [review]
LGTM.

**Review by gseriche — APPROVED** [review]
lgtm

**Pull request merged**
