### PR TITLE
(ruka) rke bump k8s to v1.25.9-rancher2-2

### PR DESCRIPTION
**Pull request by cbarria**
This upgrades the version of k8s on ruka to 1.25.9

### CODE REVIEW

**Review by dtapiacl — COMMENTED** [review]
Looks good, but I think updating to this version causes some issues when importing a cluster in Rancher, as I can no longer import RUKA back into Rancher.

**Review by jhoblitt — COMMENTED** [review]
1.29.9? We are living in the future!

**Comment by cbarria** [comment]
> 1.29.9? We are living in the future!

took it down a notch to the real value 1.25.9 lol

**Review by dtapiacl — COMMENTED** [review]
Looks good to me !

**Review by dtapiacl — APPROVED** [review]
LGTM!

**Pull request merged**
