### PR TITLE
Bump K8s to version 1.23.7 on Rancher, Luan and Gaw in Ls

### PR DESCRIPTION
**Pull request by cbarria**
Bumped version of K8s in Base, plus updated the nginx ingress, cert manager and rancher to match that version.

### CODE REVIEW

**Review by jhoblitt — CHANGES_REQUESTED** [review]
+1 on renaming the ingress install scripts.

Things which need correction:

The `cert-manager.sh` scripts need to be revised to use install the correct set of CRDs. E.g.:

```
$ diff -ru rancher.cp/cert-manager/ luan/cert-manager/
diff -u -ru rancher.cp/cert-manager/cert-manager.sh luan/cert-manager/cert-manager.sh
--- rancher.cp/cert-manager/cert-manager.sh	2022-09-07 15:00:36.788819286 -0700
+++ luan/cert-manager/cert-manager.sh	2022-09-21 16:43:56.089236095 -0700
@@ -2,21 +2,19 @@
 
 set -ex
 
-CHART_VERSION="1.9.1"
-
 helm repo add jetstack https://charts.jetstack.io
 helm repo update
 kubectl create namespace cert-manager --dry-run -o yaml | kubectl apply -f -
 
 # helm managment of the CRDs did not work when tested
-kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v${CHART_VERSION}/cert-manager.crds.yaml
+kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.crds.yaml
 
 helm upgrade --install \
-  --atomic \
   cert-manager jetstack/cert-manager \
   --create-namespace --namespace cert-manager \
-  --version v${CHART_VERSION} \
-  --set installCRDS=false
+  --version v1.9.1 \
+  --set installCRDS=false \
+  --atomic
 
 cat > secret.yaml << END
 apiVersion: v1
```

The [Bump cert-manager, ingress-nginx and rancher versions to match k8s](https://github.com/lsst-it/k8s-cookbook/pull/107/commits/94bc2f2b11ee3333e3035b27273d26c084466e1f) commit message is a little confusing.  It would probably be better to state either the versions the charts are being bumped to or to state the reason why the change is being made. E.g. "... for compat. with k8s 1.23"

The [Add values.yaml](https://github.com/lsst-it/k8s-cookbook/pull/107/commits/124b24b1f6a6271da2f620ff33c710d4a201ec18) commit should be part of the same commit which is updating `rancher.sh`.

The [Bump rke Version to 1.23.7](https://github.com/lsst-it/k8s-cookbook/pull/107/commits/a47dd1fa2d0e96b1ef0aaffb2d1de4eb4c71088f) commit says "rke version" but should say "k8s version" (the rke version would be 1.3.12 but isn't controlled by this repo).  This commit also has changes to `rancher.sh` should should be in a separate commit.

Minor quibbles:

- While grammatically correct, It is not conventional to put a `.` at the end of the PR title.
- It is probably better to use `ls` instead of `base` as both the `ls` and `dev` "sites" are within the "base" or "BDC" and this PR only applies to `ls`.

**Comment by cbarria** [comment]
thanks! those are great comments, will get back when things get fixed 👍

**Review by jhoblitt — CHANGES_REQUESTED** [review]
This looks much better.

I would like to see the [(rancher.ls) Bump k8s to v1.23.7 and add values.yaml for rancher helm…](https://github.com/lsst-it/k8s-cookbook/pull/107/commits/773cde32388a41a6d385b74eb930fc699394ad0f) commit broken up and the changes related to the `rancher.sh` script be part of the [(rancher.ls) Bump helm version for cert-manager, ingress-nginx and ra…](https://github.com/lsst-it/k8s-cookbook/pull/107/commits/42ce169ea17085a206c95bf451a11ef24eef328a) commit.

**Comment by cbarria** [comment]
thanks Josh, i believe the changes are correctly breakdown this time.

**Review by jhoblitt — CHANGES_REQUESTED** [review]
This PR is very close to perfect.

The [(rancher.ls) bump rancher helm version to 2.6.6 and add values.yml](https://github.com/lsst-it/k8s-cookbook/pull/107/commits/ded116d4bfb38814f17b4aa3b9c7dda3fd905bd4) commit is completely deleting `cluster.yml` which is then re-added by [(rancher.ls) bump k8s to v1.23.7](https://github.com/lsst-it/k8s-cookbook/pull/107/commits/7253249ee01f8e31f18c0ed5d06b03ab69218274).  The deletion appears accidental and should be removed from the change set.

**Comment by cbarria** [comment]
i believe we are good now =) thanks for helping out

**Review by jhoblitt — APPROVED** [review]
A perfect PR. Well done!

**Pull request merged**
