### PR TITLE
(WIP) Nexus Repository Deployment

### PR DESCRIPTION
**Pull request by dtapiacl**
This PR is to deploy Nexus repository at the summit.

### CODE REVIEW

**Review by jhoblitt — COMMENTED** [review]
It looks like this chart can configure ldap integration. Did you test to see if that works?

**Review by jhoblitt — COMMENTED** [review]
Shouldn't there be a nexus deployment on a dev cluster as well?

**Comment by dtapiacl** [comment]
> It looks like this chart can configure ldap integration. Did you test to see if that works?

I did not use the chart to integrate LDAP on this node, but LDAP is set up and configured for auth management in the server configuration settings; I've set up a special group on FreeIPA to filter access to this host and is currently working without any issues.

**Comment by jhoblitt** [comment]
@dtapiacl I think every production service needs to have a dev instance available for others to be able to test changes.  I would also like to see as much of the configuration done via the chart.  Otherwise, we need either a README or a technote discussing the configuration.  My strong preference is for the configuration to be automated and commited to a gitrepo rather than in documentation.

**Comment by jhoblitt** [comment]
To be pedantic, I would like a dev deployment to be merged prior to this PR.

**Comment by jhoblitt** [comment]
Superseded by https://github.com/lsst-it/k8s-cookbook/pull/499

**Pull request closed without merging**
