### PR TITLE
(fleet/external-secrets) add ExternalSecretSyncError alert

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Review by cbarria — APPROVED** [review]
Looks Great 👍🏻

**Review by fbegyn — APPROVED** [review]
LGTM, but we might wanna allign all the labels before merging these requests. Alertwise and query wise these seem alright.

**Review by fbegyn — APPROVED** [review]
LGTM

**Review by fbegyn — APPROVED** [review]
LGTM

**Pull request merged**
