### PR TITLE
(ruka/loki) Add Loki user to Ruka Ceph object store

### PR DESCRIPTION
**Pull request by gseriche**

### CODE REVIEW

**Review by cbarria — CHANGES_REQUESTED** [review]
- Commit message is not Present Imperative.
- This user doesn't push credentials to 1password like the other users in the folder? is this correct?

**Review by cbarria — CHANGES_REQUESTED** [review]
dunno why i got re-requested when i already reviewed this, but it is still missing lots of stuff.

**Comment by csilva-cl** [comment]
> dunno why i got re-requested when i already reviewed this, but it is still missing lots of stuff.

I added you the review list, didn't mean to trigger a review, given the comment you left.

**Comment by gseriche** [comment]
> * Commit message is not Present Imperative.
> * This user doesn't push credentials to 1password like the other users in the folder? is this correct?

Yes, We talked with @jhoblitt  about that; the credentials don't need to be stored in 1Password: 
>  The end users do not need access to the Loki bucket(s).  Also, Loki will be deployed in the same cluster as RGW, so pushing the credentials out to 1Pass is unnecessary.

**Review by dtapiacl — APPROVED** [review]
LGTM.

**Pull request merged**
