### PR TITLE
Update rook-ceph config for TTS

### PR DESCRIPTION
**Pull request by cbarria**
quotas been reach for s3 and the replication pool, plus some config debt on dashboard.

### CODE REVIEW

**Review by jhoblitt — COMMENTED** [review]
I'm not excited about using `ceph-storagepool.yaml`  as a file name. The resource kind is `CephBlockPool` and the name is `replicapool` -- neither of which is reflected in the file name.

**Comment by cbarria** [comment]
was the only filename in the directory without a dash, all others have rook- or ceph- but you are right, the resource is called `CephBlockPool`, changes were reversed. 👍🏻

**Review by jhoblitt — APPROVED** [review]

**Comment by jhoblitt** [comment]
Please don't merge this branch while it contains a merge commit.

**Comment by cbarria** [comment]
i manage to notice first! its fixed now and reflects the real quota, will have to set route53 tho

**Pull request merged**
